// Regenerates src/app/core/icons.ts from lucide-static (ISC license).
// Run after adding a name to ICONS: node scripts/build-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const ICONS = [
  'activity', 'alert-triangle', 'arrow-left', 'book-open', 'check', 'chevron-down',
  'chevron-left', 'chevron-right', 'circle-check', 'circle-dot', 'circle-slash', 'circle-x',
  'clock', 'copy', 'cpu', 'download', 'external-link', 'file', 'folder', 'git-branch',
  'history', 'info', 'key', 'layers', 'list', 'loader', 'menu',
  'message-circle-question-mark', 'moon', 'pencil', 'play', 'plus', 'radio', 'refresh-cw',
  'save', 'search', 'server', 'sparkles', 'square-pen', 'sun', 'trash-2', 'upload',
  'workflow', 'x',
];

const symbols = ICONS.map((name) => {
  const svg = readFileSync(new URL(`../node_modules/lucide-static/icons/${name}.svg`, import.meta.url), 'utf8');
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  return `<symbol id="${name}" viewBox="0 0 24 24">${inner}</symbol>`;
}).join('');

const out = `// GENERATED by scripts/build-icons.mjs from lucide-static (ISC) — do not edit by hand.
export const lucideSprite = \`<svg xmlns="http://www.w3.org/2000/svg" style="display:none">${symbols}</svg>\`;
`;
writeFileSync(new URL('../src/app/core/icons.ts', import.meta.url), out);
console.log(`wrote ${ICONS.length} icons`);
